services:
  chatmail:
    image: chatmail-relay-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatmail
    privileged: true  # for systemd to work
    cgroup: "host"  # for systemd to work
    restart: unless-stopped
    ports:
      - "25:25"
      - "8080:80"
      - "143:143"
      - "9443:443"
      - "465:465"
      - "587:587"
      - "993:993"
      - "3340:3340"
      - "3478:3478"
    volumes:
      - ./acme:/var/lib/acme:rw  # save certs to avoid request them again in case something gooes wrong and you need to start from the beginning
      - ./dkimkeys:/etc/dkimkeys:rw  # dkimkeys for backups and migrating to a new machine
      - ./vmail:/home/vmail:rw  # accounts for backups and migrating to a new machine
      - ./postfix:/var/spool/postfix:rw  # for backups and migrating to a new machine
      - /sys/fs/cgroup:/sys/fs/cgroup:rw  # for systemd to work
      # - ./chatmail.ini:/opt/chatmail/chatmail.ini
    tmpfs:  # for systemd to work
      - /run
      - /run/lock
