services:
  chatmail:
    image: chatmail-relay-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatmail
    privileged: true  # for systemd to work
    cgroup: "host"  # for systemd to work
    restart: unless-stopped
    ports:
      - "25:25"
      - "80:80"
      - "143:143"
      - "443:443"
      - "465:465"
      - "587:587"
      - "993:993"
      - "3340:3340"
      - "3478:3478"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw  # for systemd to work
      - chatmail_var:/var
      - chatmail_home:/home
      - chatmail_opt:/opt
      - chatmail_etc:/etc
      - chatmail_root:/root
      - chatmail_usr:/usr
    tmpfs:  # for systemd to work
      - /run
      - /run/lock

volumes:
  chatmail_var:
  chatmail_home:
  chatmail_opt:
  chatmail_etc:
  chatmail_root:
  chatmail_usr:
